#!/bin/bash
source sources/display_help.sh
source sources/display_ascii_start.sh
source sources/start_install.sh
source sources/start_configuration.sh

clear
display_ascii_start
echo ""
echo "Test de connexion ..."
ping -c 3 8.8.8.8
echo ""
echo ""
if [ ${?} = '0' ]; then
	display_help
	echo ""
	read -p "Démarrer l'installation ? (o/n)" CHOICE_START

	if [[ $CHOICE_START =~ ^[Oo]$ ]]; then
		start_install
		echo ""
		echo ""
		echo ""
		echo "Installation terminée..."
		sleep 1
		echo "Nous allons maintenant configurer votre environnement..."
		sleep 3
		start_configuration
		echo "Votre environnement de travail EPITECH est prêt, bon courage."
		echo "Si vous avez rencontrez des problème pendant l'execution de ce script, faites m'en part ;-)"
	else
		echo "Abort..."
	fi
else
	echo "Vous devez être connecté à internet pour utiliser ce script"
	echo "Abort..."
	exit 1
fi
exit 0
